export const COPY = {
  appName: "Expense Tracker",
  tagline: "Where did January go?",
  documentTitle: "Expense Tracker · Where did January go?",
  historyTitle: "Expense History",
  navHistory: "The books",
  addExpense: "Log it",
  addCategory: "New habit",
  saveCategory: "Keep it",
  loading: "Counting receipts…",
  addExpenseModal: "What did it cost?",
  addCategoryModal: "Name the habit",
  editExpenseModal: "Fix the receipt",
  updateExpense: "Save it",
  submitting: "Logging…",
  adding: "Naming…",
  emptyMonth:
    "Quiet month. Either you're thriving, or you forgot to log it.",
  emptyTally: "Nothing to split yet.",
  descriptionPlaceholder: "Coffee, taxi, the good kind of mistake",
  categoryPlaceholder: "Snacks, rent, the other one",
  categorySelectPlaceholder: "Pick a bucket",
  emojiLabel: "Give it a face",
  deleteTitle: "Take it back",
  deleteConfirm: "This receipt never happened.",
  deleteFailed: "Could not delete that one. Try again.",
  futureDate: "Tomorrow isn't here yet.",
  totalLabel: "THE TALLY",
} as const;
